In [1]:
import pandas as pd

In [42]:
df = pd.read_csv(r"D:\Dhika Ramadhan Saputra\Data Analist\Kebutuhan\layoffs.csv")

In [44]:
df2 = pd.read_table(r"D:\Dhika Ramadhan Saputra\Data Analist\Kebutuhan\countries of the world.txt")

In [46]:
df3 = pd.read_json(r"D:\Dhika Ramadhan Saputra\Data Analist\Kebutuhan\json_sample.json")

In [48]:
df4 = pd.read_excel(r"D:\Dhika Ramadhan Saputra\Data Analist\Kebutuhan\Excel Charts Tutorial File.xlsx")

In [102]:
df

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,Atlassian,Sydney,Other,500.0,0.0500,3/6/2023,Post-IPO,Australia,210.0000
1,SiriusXM,New York City,Media,475.0,0.0800,3/6/2023,Post-IPO,United States,525.0000
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0000
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0000
4,Loft,Sao Paulo,Real Estate,340.0,0.1500,3/3/2023,Unknown,Brazil,788.0000
5,Embark Trucks,SF Bay Area,Transportation,230.0,0.7000,3/3/2023,Post-IPO,United States,317.0000
6,Lendi,Sydney,Real Estate,100.0,NaN,3/3/2023,Unknown,Australia,59.0000
7,UserTesting,SF Bay Area,Marketing,63.0,NaN,3/3/2023,Acquired,United States,152.0000
8,Airbnb,SF Bay Area,NaN,30.0,NaN,3/3/2023,Post-IPO,United States,6400.0000
9,Accolade,Seattle,Healthcare,NaN,NaN,3/3/2023,Post-IPO,United States,458.0000
10,Indigo,Boston,Other,NaN,NaN,3/3/2023,Series F,United States.,1200.0000
11,Zscaler,SF Bay Area,Security,177.0,0.0300,3/2/2023,Post-IPO,United States,148.0000
12,MasterClass,SF Bay Area,Education,79.0,NaN,3/2/2023,Series E,United States,461.0000
13,Ambev Tech,Blumenau,Food,50.0,NaN,3/2/2023,Acquired,Brazil,NaN
14,Fittr,Pune,Fitness,30.0,0.1100,3/2/2023,Series A,India,13.0000
15,CNET,SF Bay Area,Media,12.0,0.1000,3/2/2023,Acquired,United States,20.0000
16,Flipkart,Bengaluru,Retail,NaN,NaN,3/2/2023,Acquired,India,12900.0000
17,Kandela,Los Angeles,Consumer,NaN,1.0000,3/2/2023,Acquired,United States,NaN
18,Truckstop.com,Boise,Logistics,NaN,NaN,3/2/2023,Acquired,United States,NaN
19,Thoughtworks,Chicago,Other,500.0,0.0400,3/1/2023,Post-IPO,United States,748.0000
20,iFood,Sao Paulo,Food,355.0,0.0600,3/1/2023,Subsidiary,Brazil,2100.0000
21,Color Health,SF Bay Area,Healthcare,300.0,NaN,3/1/2023,Series E,United States,482.0000
22,Waymo,SF Bay Area,Transportation,209.0,0.0800,3/1/2023,Subsidiary,United States,5500.0000
23,PayFit,Paris,HR,200.0,0.2000,3/1/2023,Series E,France,495.0000
24,Yellow.ai,SF Bay Area,Support,200.0,NaN,3/1/2023,Series C,United States,102.0000
25,Sonder,SF Bay Area,Travel,100.0,0.1400,3/1/2023,Post-IPO,United States,839.0000
26,Protego Trust Bank,Seattle,Crypto,NaN,0.5000,3/1/2023,Series A,United States,70.0000
27,Electronic Arts,Baton Rouge,Consumer,200.0,NaN,2/28/2023,Post-IPO,United States,2.0000
28,Eventbrite,SF Bay Area,Consumer,80.0,0.0800,2/28/2023,Post-IPO,United States,557.0000
29,DUX Education,Bengaluru,Education,NaN,1.0000,2/28/2023,Unknown,India,NaN
30,MeridianLink,Los Angeles,Finance,NaN,0.0900,2/28/2023,Post-IPO,United States,485.0000
31,Sono Motors,Munich,Transportation,300.0,NaN,2/27/2023,Post-IPO,Germany,126.0000
32,Cerebral,SF Bay Area,Healthcare,285.0,0.1500,2/27/2023,Series C,United States,462.0000
33,Amount,Chicago,Finance,130.0,0.2500,2/27/2023,Unknown,United States,283.0000
34,Palantir,Denver,Data,75.0,0.0200,2/27/2023,Post-IPO,United States.,3000.0000
35,Outreach,Seattle,Sales,70.0,0.0700,2/27/2023,Series G,United States,489.0000
36,Stytch,SF Bay Area,Security,19.0,0.2500,2/27/2023,Series B,United States,126.0000
37,BitSight,Tel Aviv,Security,40.0,NaN,2/26/2023,Unknown,Israel,401.0000
38,Twitter,SF Bay Area,Consumer,200.0,0.1000,2/25/2023,Post-IPO,United States,12900.0000
39,Ericsson,Stockholm,Other,8500.0,0.0800,2/24/2023,Post-IPO,Sweden,663.0000
40,SAP Labs,Bengaluru,Other,300.0,NaN,2/24/2023,Subsidiary,India,1300.0000
41,Velodyne Lidar,SF Bay Area,Transportation,220.0,NaN,2/24/2023,Acquired,United States,575.0000
42,Medallia,SF Bay Area,Support,59.0,NaN,2/24/2023,Acquired,United States,325.0000
43,Eat Just,SF Bay Area,Food,40.0,NaN,2/24/2023,Unknown,United States,465.0000
44,Lucira Health,SF Bay Area,Healthcare,26.0,NaN,2/24/2023,Post-IPO,United States,132.0000
45,Stax,Orlando,Finance,24.0,NaN,2/24/2023,Series D,United States,263.0000
46,Poshmark,SF Bay Area,Retail,NaN,0.0200,2/24/2023,Acquired,United States,153.0000
47,Merative,Ann Arbor,Healthcare,200.0,0.1000,2/23/2023,Acquired,United States,NaN
48,OneFootball,Berlin,Marketing,150.0,0.3200,2/23/2023,Series D,Germany,442.0000
49,The Iconic,Sydney,Retail,69.0,0.0600,2/23/2023,Unknown,Australia,NaN
50,EVgo,Los Angeles,Transportation,40.0,NaN,2/23/2023,Post-IPO,United States,400.0000
51,StrongDM,SF Bay Area,Infrastructure,40.0,NaN,2/23/2023,Series B,United States,76.0000
52,Dapper Labs,Vancouver,Crypto,NaN,0.2000,2/23/2023,Series D,United States,607.0000
53,Messari,New York City,Crypto,NaN,0.1500,2/23/2023,Series B,United States,61.0000
54,Vibrent Health,Washington D.C.,Healthcare,NaN,0.1300,2/23/2023,Unknown,United States,NaN
55,Synamedia,London,Media,200.0,0.1200,2/22/2023,Unknown,United Kingdom,NaN
56,TaskUs,San Antonio,Support,186.0,NaN,2/22/2023,Post-IPO,United States,279.0000
57,Arch Oncology,St. Louis,Healthcare,NaN,NaN,2/22/2023,Series C,United States,155.0000
58,Immutable,Sydney,Crypto,NaN,0.1100,2/22/2023,Series C,Australia,279.0000
59,Jounce Therapeutics,Boston,Healthcare,NaN,0.5700,2/22/2023,Acquired,United States,194.0000
60,Locomation,Pittsburgh,Transportation,NaN,1.0000,2/22/2023,Seed,United States,57.0000
61,Polygon,Bengaluru,Crypto,100.0,0.2000,2/21/2023,Unknown,India,451.0000
62,Crunchyroll,Tokyo,Media,85.0,NaN,2/21/2023,Unknown,Japan,26.0000
63,Ethos Life,SF Bay Area,Finance,50.0,NaN,2/21/2023,Series D,United States,406.0000
64,Bolt,Lagos,Transportation,17.0,NaN,2/21/2023,Series F,Nigeria,NaN
65,Criteo,Paris,Marketing,NaN,NaN,2/21/2023,Post-IPO,France,61.0000
66,Green Labs,Seoul,Food,NaN,NaN,2/21/2023,Series C,South Korea,214.0000
67,PeerStreet,Los Angeles,Real Estate,NaN,NaN,2/21/2023,Series C,United States,121.0000
68,Zalando,Berlin,Retail,NaN,NaN,2/21/2023,Post-IPO,Germany,467.0000
69,MyGate,Bengaluru,Other,200.0,0.3000,2/20/2023,Series B,India,79.0000
70,Fireblocks,New York City,Crypto,30.0,0.0500,2/20/2023,Series E,United States,1000.0000
71,Kinde,Sydney,Other,8.0,0.2800,2/20/2023,Seed,Australia,10.0000
72,Fipola,Chennai,Food,NaN,1.0000,2/20/2023,Series A,United States,9.0000
73,HP,Tel Aviv,Hardware,100.0,NaN,2/19/2023,Post-IPO,Israel,4200.0000
74,Tencent,Shenzen,Consumer,300.0,NaN,2/17/2023,Post-IPO,China,12600.0000
75,Evernote,SF Bay Area,Consumer,129.0,NaN,2/17/2023,Acquired,United States,290.0000
76,Chipper Cash,SF Bay Area,Finance,100.0,0.3300,2/17/2023,Series C,United States,302.0000
77,Digimarc,Portland,Other,NaN,NaN,2/17/2023,Post-IPO,United States,105.0000
78,Reserve,SF Bay Area,Crypto,NaN,NaN,2/17/2023,Unknown,United States,NaN
79,DocuSign,SF Bay Area,Sales,680.0,0.1000,2/16/2023,Post-IPO,United States,536.0000
80,Pico Interactive,SF Bay Area,Other,400.0,0.2000,2/16/2023,Acquired,United States,62.0000
81,The RealReal,SF Bay Area,Retail,230.0,0.0700,2/16/2023,Post-IPO,United States,356.0000
82,Smartsheet,Seattle,Other,85.0,0.0300,2/16/2023,Post-IPO,United States,152.0000
83,Convoy,Atlanta,Logistics,NaN,NaN,2/16/2023,Series E,United States,1100.0000
84,Wix,Tel Aviv,Marketing,370.0,0.0600,2/15/2023,Post-IPO,Israel,58.0000
85,ServiceTitan,Los Angeles,Sales,221.0,0.0800,2/15/2023,Series G,United States,1100.0000
86,Neon,Sao Paulo,Finance,210.0,0.0900,2/15/2023,Series D,Brazil,720.0000
87,Jellysmack,Paris,Media,208.0,NaN,2/15/2023,Series C,France,22.0000
88,DigitalOcean,New York City,Infrastructure,200.0,0.1100,2/15/2023,Post-IPO,United States,491.0000
89,Sprinklr,New York City,Support,100.0,0.0400,2/15/2023,Post-IPO,United States,429.0000
90,Betterment,New York City,Finance,28.0,NaN,2/15/2023,Series F,United States,435.0000
91,Divvy Homes,SF Bay Area,Real Estate,NaN,NaN,2/15/2023,Series B,United States,180.0000
92,Milkrun,Sydney,Food,NaN,0.2000,2/15/2023,Series A,Australia,86.0000
93,Momentive,SF Bay Area,Marketing,NaN,0.1400,2/15/2023,Post-IPO,United States,1100.0000
94,Observe.AI,SF Bay Area,Support,NaN,NaN,2/15/2023,Series C,United States,214.0000
95,Religion of Sports,Los Angeles,Media,NaN,NaN,2/15/2023,Series B,United States,63.0000
96,Tackle,Boise,Other,NaN,0.1500,2/15/2023,Series C,United States,148.0000
97,Vicarious Surgical,Boston,Healthcare,NaN,0.1400,2/15/2023,Post-IPO,United States,185.0000
98,CommerceHub,Albany,Retail,371.0,0.3100,2/14/2023,Acquired,United States,NaN
99,HackerEarth,SF Bay Area,HR,NaN,0.0800,2/14/2023,Series B,United States,11.0000
100,PhableCare,Bengaluru,Healthcare,NaN,0.7000,2/14/2023,Series B,India,40.0000
101,Udemy,SF Bay Area,Education,NaN,0.1000,2/14/2023,Post-IPO,United States,311.0000
102,Twilio,SF Bay Area,Other,1500.0,0.1700,2/13/2023,Post-IPO,United States.,614.0000
103,Electric,New York City,Other,141.0,0.2500,2/13/2023,Series D,United States,212.0000
104,EMX Digital,New York City,Marketing,100.0,1.0000,2/13/2023,Unknown,United States,NaN
105,PetLove,Sao Paulo,Retail,94.0,NaN,2/13/2023,Series C,Brazil,225.0000
106,iRobot,Boston,Consumer,85.0,0.0700,2/13/2023,Acquired,United States,30.0000
107,Collective Health,SF Bay Area,Healthcare,54.0,NaN,2/13/2023,Series F,United States,719.0000
108,Magic Eden,SF Bay Area,Crypto,22.0,NaN,2/13/2023,Series B,United States,170.0000
109,Casavo,Milan,Real Estate,NaN,0.3000,2/13/2023,Unknown,Italy,708.0000
110,Foodpanda,Singapore,Food,NaN,NaN,2/13/2023,Acquired,Singapore,749.0000
111,Getir,London,Food,NaN,NaN,2/13/2023,Series E,United Kingdom,1800.0000
112,LinkedIn,SF Bay Area,HR,NaN,NaN,2/13/2023,Acquired,United States,154.0000
113,Moladin,Jakarta,Transportation,360.0,0.1100,2/12/2023,Series B,Indonesia,138.0000
114,TripleLift,New York City,Marketing,100.0,0.2000,2/10/2023,Acquired,United States,16.0000
115,TikTok India,Mumbai,Consumer,40.0,NaN,2/10/2023,Acquired,India,9400.0000
116,Open Co,Sao Paulo,Finance,NaN,NaN,2/10/2023,Series D,Brazil,140.0000
117,Rigetti Computing,SF Bay Area,Hardware,NaN,0.2800,2/10/2023,Post-IPO,United States,298.0000
118,Yahoo,SF Bay Area,Consumer,1600.0,0.2000,2/9/2023,Acquired,United States,6.0000
119,Misfits Market,Philadelphia,Food,649.0,0.3300,2/9/2023,Series C,United States,526.0000
120,Deliveroo,London,Food,350.0,0.0900,2/9/2023,Post-IPO,United Kingdom,1700.0000
121,Olive AI,Columbus,Healthcare,215.0,0.3500,2/9/2023,Series H,United States,856.0000
122,Oportun,SF Bay Area,Finance,155.0,0.1000,2/9/2023,Post-IPO,United States,566.0000
123,GitLab,SF Bay Area,Product,130.0,0.0700,2/9/2023,Post-IPO,United States,413.0000
124,Bark,New York City,Retail,126.0,0.1200,2/9/2023,Post-IPO,United States,NaN
125,Nomad Health,New York City,Healthcare,119.0,0.1700,2/9/2023,Unknown,United States,218.0000
126,Veriff,Tallinn,Security,66.0,0.1200,2/9/2023,Series C,Estonia,192.0000
127,REE Automotive,Tel Aviv,Transportation,31.0,0.1100,2/9/2023,Post-IPO,Israel,317.0000
128,GitHub,SF Bay Area,Product,NaN,0.1000,2/9/2023,Acquired,United States,350.0000
129,Quillt,St. Louis,Media,NaN,NaN,2/9/2023,Unknown,United States,NaN
130,WeTrade,Bengaluru,Crypto,NaN,1.0000,2/9/2023,Unknown,India,NaN
131,GoDaddy,Phoenix,Marketing,530.0,0.0800,2/8/2023,Post-IPO,United States,800.0000
132,Affirm,SF Bay Area,Finance,500.0,0.1900,2/8/2023,Post-IPO,United States,1500.0000
133,Gusto,SF Bay Area,HR,126.0,0.0500,2/8/2023,Series E,United States,746.0000
134,Gong,SF Bay Area,Sales,80.0,0.0700,2/8/2023,Series E,United States,583.0000
135,Beam Benefits,Columbus,Healthcare,31.0,0.0800,2/8/2023,Series E,United States,168.0000
136,Equitybee,SF Bay Area,Finance,24.0,0.2500,2/8/2023,Series B,United States,85.0000
137,Baraja,Sydney,Transportation,NaN,0.7500,2/8/2023,Unknown,Australia,63.0000
138,Koho,Toronto,Finance,NaN,0.1400,2/8/2023,Series D,Canada,278.0000
139,Medly,New York City,Healthcare,NaN,1.0000,2/8/2023,Series C,United States,100.0000
140,Nearmap,Sydney,Construction,NaN,0.2000,2/8/2023,Acquired,Australia,15.0000
141,Zoom,SF Bay Area,Other,1300.0,0.1500,2/7/2023,Post-IPO,United States,276.0000
142,eBay,SF Bay Area,Retail,500.0,0.0400,2/7/2023,Post-IPO,United States,1200.0000
143,SecureWorks,Atlanta,Security,212.0,0.0900,2/7/2023,Post-IPO,United States,83.0000
144,Salesloft,Atlanta,Sales,100.0,0.1000,2/7/2023,Acquired,United States,245.0000
145,Openpay,Melbourne,Finance,83.0,1.0000,2/7/2023,Post-IPO,Australia,299.0000
146,LearnUpon,Dublin,Education,27.0,0.0900,2/7/2023,Private Equity,Ireland,56.0000
147,Sana Benefits,Austin,HR,NaN,0.1900,2/7/2023,Series B,United States,106.0000
148,Dell,Austin,Hardware,6650.0,0.0500,2/6/2023,Post-IPO,United States,NaN
149,Loggi,Sao Paulo,Logistics,300.0,0.0700,2/6/2023,Series F,Brazil,507.0000
150,Catch.com.au,Melbourne,Retail,100.0,NaN,2/6/2023,Acquired,Australia,80.0000
151,VinFast US,Los Angeles,Transportation,80.0,NaN,2/6/2023,Subsidiary,United States,NaN
152,Drift,Boston,Marketing,59.0,NaN,2/6/2023,Acquired,United States,107.0000
153,Pocket Aces,Mumbai,Media,50.0,0.2500,2/6/2023,Unknown,India,19.0000
154,Clari,SF Bay Area,Sales,20.0,NaN,2/6/2023,Series F,United States,496.0000
155,C6 Bank,Sao Paulo,Finance,NaN,NaN,2/6/2023,Unknown,Brazil,2300.0000
156,Daraz,Singapore,Retail,NaN,0.1100,2/6/2023,Unknown,Singapore,NaN
157,TenureX,Tel Aviv,Finance,NaN,NaN,2/6/2023,Seed,Israel,6.0000
158,Kyruus,Boston,Healthcare,70.0,NaN,2/5/2023,Unknown,United States,183.0000
159,Lightico,Tel Aviv,Finance,20.0,0.2500,2/5/2023,Series B,Israel,42.0000
160,FarEye,New Delhi,Logistics,90.0,NaN,2/3/2023,Series E,India,150.0000
161,Protocol Labs,SF Bay Area,Crypto,89.0,0.2000,2/3/2023,Unknown,United States,10.0000
162,Finder,Sydney,Retail,NaN,0.1500,2/3/2023,Unknown,Australia,30.0000
163,Byju's,Bengaluru,Education,1500.0,NaN,2/2/2023,Private Equity,India,5500.0000
164,Okta,SF Bay Area,Security,300.0,0.0500,2/2/2023,Post-IPO,United States,1200.0000
165,Autodesk,SF Bay Area,Other,250.0,0.0200,2/2/2023,Post-IPO,United States,NaN
166,Mindstrong,SF Bay Area,Healthcare,127.0,NaN,2/2/2023,Series C,United States,160.0000
167,NCC Group,Manchester,Security,125.0,0.0700,2/2/2023,Post-IPO,United Kingdom,NaN
168,Miro,SF Bay Area,Other,119.0,0.0700,2/2/2023,Series C,United States,476.0000
169,Getir,New York City,Food,100.0,NaN,2/2/2023,Series E,United States,1800.0000
170,Highspot,Seattle,Sales,100.0,0.1000,2/2/2023,Series F,United States,644.0000
171,Bittrex,Seattle,Crypto,80.0,NaN,2/2/2023,Unknown,United States,NaN
172,Snowplow,London,Data,40.0,NaN,2/2/2023,Series B,United States,55.0000
173,Articulate,New York City,Education,38.0,NaN,2/2/2023,Series A,United States,1500.0000
174,Desktop Metal,Boston,Other,NaN,NaN,2/2/2023,Post-IPO,United States,811.0000
175,Getaround,SF Bay Area,Transportation,NaN,0.1000,2/2/2023,Post-IPO,United States,948.0000
176,NCSoft,Seoul,Consumer,NaN,0.2000,2/2/2023,Post-IPO,South Korea,240.0000
177,Talkdesk,SF Bay Area,Support,NaN,NaN,2/2/2023,Series D,United States,497.0000
178,Splunk,SF Bay Area,Data,325.0,0.0400,2/1/2023,Post-IPO,United States,2400.0000
179,Pinterest,SF Bay Area,Consumer,150.0,NaN,2/1/2023,Post-IPO,United States,1500.0000
180,DraftKings,Boston,Consumer,140.0,0.0400,2/1/2023,Post-IPO,United States,719.0000
181,Cyren,Washington D.C.,Security,121.0,NaN,2/1/2023,Post-IPO,United States,161.0000
182,Workato,SF Bay Area,Other,90.0,0.1000,2/1/2023,Series E,United States,415.0000
183,VerticalScope,Toronto,Media,60.0,0.2200,2/1/2023,Post-IPO,Canada,NaN
184,Wheel,Austin,Healthcare,56.0,0.2800,2/1/2023,Series C,United States,215.0000
185,Chainalysis,New York City,Crypto,44.0,0.0500,2/1/2023,Series F,United States,536.0000
186,Appgate,Miami,Security,34.0,0.0800,2/1/2023,Post-IPO,United States,NaN
187,Exterro,Portland,Legal,24.0,0.0300,2/1/2023,Private Equity,United States,100.0000
188,TheSkimm,New York City,Media,17.0,0.1000,2/1/2023,Series C,United States,28.0000
189,Ada,Toronto,Support,NaN,NaN,2/1/2023,Series C,Canada,190.0000
190,Bustle Digital Group,New York City,Media,NaN,0.0800,2/1/2023,Series E,United States,80.0000
191,Frequency Therapeutics,Boston,Healthcare,NaN,0.5000,2/1/2023,Post-IPO,United States,76.0000
192,MariaDB,Helsinki,Data,NaN,0.0800,2/1/2023,Post-IPO,Finland,245.0000
193,Match Group,New York City,Consumer,NaN,0.0800,2/1/2023,Post-IPO,United States,NaN
194,Omnipresent,London,HR,NaN,NaN,2/1/2023,Series B,United States,137.0000
195,Picnic,Seattle,Food,NaN,NaN,2/1/2023,Unknown,United States,52.0000
196,Rivian,Detroit,Transportation,NaN,0.0600,2/1/2023,Post-IPO,United States,10700.0000
197,PayPal,SF Bay Area,Finance,2000.0,0.0700,1/31/2023,Post-IPO,United States,216.0000
198,NetApp,SF Bay Area,Data,960.0,0.0800,1/31/2023,Post-IPO,United States,NaN
199,Workday,SF Bay Area,HR,525.0,0.0300,1/31/2023,Post-IPO,United States,230.0000
200,HubSpot,Boston,Marketing,500.0,0.0700,1/31/2023,Post-IPO,United States,100.0000
201,Upstart,SF Bay Area,Finance,365.0,0.2000,1/31/2023,Post-IPO,United States,144.0000
202,Software AG,Frankfurt,Data,200.0,0.0400,1/31/2023,Post-IPO,Germany,344.0000
203,Wish,SF Bay Area,Retail,150.0,0.1700,1/31/2023,Post-IPO,United States,1600.0000
204,Wefox,Berlin,Finance,100.0,NaN,1/31/2023,Series D,Germany,1300.0000
205,Tilting Point,New York City,Consumer,60.0,0.1400,1/31/2023,Unknown,United States,235.0000
206,Gokada,Lagos,Transportation,54.0,NaN,1/31/2023,Unknown,Nigeria,12.0000
207,AU10TIX,Tel Aviv,Security,19.0,0.0900,1/31/2023,Unknown,Israel,80.0000
208,National Instruments,Austin,Hardware,NaN,0.0400,1/31/2023,Post-IPO,United States,NaN
209,OpenText,Waterloo,Data,NaN,0.0800,1/31/2023,Post-IPO,Canada,1100.0000
210,Philips,Amsterdam,Healthcare,6000.0,0.1300,1/30/2023,Post-IPO,Netherlands,NaN
211,OLX Group,Amsterdam,Marketing,1500.0,0.1500,1/30/2023,Acquired,Netherlands,NaN
212,Arrival,London,Transportation,800.0,0.5000,1/30/2023,Post-IPO,United Kingdom,629.0000
213,Groupon,Chicago,Retail,500.0,NaN,1/30/2023,Post-IPO,United States,1400.0000
214,Intel,SF Bay Area,Hardware,343.0,NaN,1/30/2023,Post-IPO,United States,12.0000
215,Glovo,Barcelona,Food,250.0,0.0600,1/30/2023,Acquired,Spain,1200.0000
216,Delivery Hero,Berlin,Food,156.0,0.0400,1/30/2023,Post-IPO,Germany,9900.0000
217,Impossible Foods copy,SF Bay Area,Food,140.0,0.2000,1/30/2023,Series H,United States,1900.0000
218,Chrono24,Karlsruhe,Retail,65.0,0.1300,1/30/2023,Series C,Germany,205.0000
219,BM Technologies,Philadelphia,Finance,NaN,0.2500,1/30/2023,Post-IPO,United States,NaN
220,Olist,Curitiba,Retail,NaN,NaN,1/30/2023,Series E,Brazil,322.0000
221,Oyster,Charlotte,HR,NaN,NaN,1/30/2023,Series C,United States,224.0000
222,Prime Trust,Las Vegas,Crypto,NaN,0.3300,1/30/2023,Series B,United States,176.0000
223,Quantum SI,New Haven,Healthcare,NaN,0.1200,1/30/2023,Post-IPO,United States,425.0000
224,SoFi,SF Bay Area,Finance,NaN,NaN,1/30/2023,Post-IPO,United States,3000.0000
225,Hoxhunt,Helsinki,Security,NaN,NaN,1/29/2023,Series B,Finland,43.0000
226,Me Poupe,Sao Paulo,Finance,60.0,0.5000,1/28/2023,Unknown,Brazil,NaN
227,CoinTracker,SF Bay Area,Crypto,19.0,NaN,1/28/2023,Series A,United States,101.0000
228,SSense,Montreal,Retail,138.0,0.0700,1/27/2023,Series A,Canada,NaN
229,DealShare,Bengaluru,Retail,100.0,0.0600,1/27/2023,Series E,India,390.0000
230,Ruggable,Los Angeles,Retail,100.0,NaN,1/27/2023,Seed,United States,NaN
231,Synopsys,SF Bay Area,Other,100.0,NaN,1/27/2023,Post-IPO,United States,NaN
232,Heycar,Berlin,Transportation,73.0,NaN,1/27/2023,Unknown,Germany,NaN
233,Matrixport,Singapore,Crypto,29.0,0.1000,1/27/2023,Series C,Singapore,100.0000
234,Shakepay,Montreal,Crypto,21.0,0.2500,1/27/2023,Series A,Canada,45.0000
235,#Paid,Toronto,Marketing,19.0,0.1700,1/27/2023,Series B,Canada,21.0000
236,Decent,SF Bay Area,Healthcare,NaN,NaN,1/27/2023,Series A,United States,18.0000
237,Feedzai,Coimbra,Finance,NaN,NaN,1/27/2023,Unknown,Portugal,273.0000
238,Nate,New York City,Retail,NaN,NaN,1/27/2023,Series A,United States,47.0000
239,SAP,Walldorf,Other,3000.0,0.0300,1/26/2023,Post-IPO,Germany,1300.0000
240,Confluent,SF Bay Area,Data,221.0,0.0800,1/26/2023,Post-IPO,United States,455.0000
241,DriveWealth,Jersey City,Finance,NaN,0.2000,1/26/2023,Series D,United States,550.0000
242,Mode Global,London,Finance,NaN,1.0000,1/26/2023,Post-IPO,United Kingdom,NaN
243,Plus One Robotics,San Antonio,Other,NaN,0.1000,1/26/2023,Series B,United States,43.0000
244,Quora,SF Bay Area,Consumer,NaN,NaN,1/26/2023,Series D,United States,226.0000

In [100]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2361 entries, 0 to 2360
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   company                2361 non-null   object
 1   location               2361 non-null   object
 2   industry               2357 non-null   object
 3   total_laid_off         1621 non-null   float64
 4   percentage_laid_off    1576 non-null   float64
 5   date                   2360 non-null   object
 6   stage                  2355 non-null   object
 7   country                2361 non-null   object
 8   funds_raised_millions  2152 non-null   float64
dtypes: float64(3), object(6)
memory usage: 166.1+ KB

In [74]:
df.shape

(2361, 9)

In [106]:
df.head(10)

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0
5,Embark Trucks,SF Bay Area,Transportation,230.0,0.70,3/3/2023,Post-IPO,United States,317.0
6,Lendi,Sydney,Real Estate,100.0,NaN,3/3/2023,Unknown,Australia,59.0
7,UserTesting,SF Bay Area,Marketing,63.0,NaN,3/3/2023,Acquired,United States,152.0
8,Airbnb,SF Bay Area,NaN,30.0,NaN,3/3/2023,Post-IPO,United States,6400.0
9,Accolade,Seattle,Healthcare,NaN,NaN,3/3/2023,Post-IPO,United States,458.0

In [110]:
df.tail(10)

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
2351,Service,Los Angeles,Travel,NaN,1.00,3/16/2020,Seed,United States,5.1
2352,HopSkipDrive,Los Angeles,Transportation,8.0,0.10,3/13/2020,Unknown,United States,45.0
2353,Panda Squad,SF Bay Area,Consumer,6.0,0.75,3/13/2020,Seed,United States,1.0
2354,Tamara Mellon,Los Angeles,Retail,20.0,0.40,3/12/2020,Series C,United States,90.0
2355,EasyPost,Salt Lake City,Logistics,75.0,NaN,3/11/2020,Series A,United States,12.0
2356,Blackbaud,Charleston,Other,500.0,0.14,NaN,Post-IPO,United States,NaN
2357,Yahoo,SF Bay Area,Consumer,1600.0,0.20,2/9/2023,Acquired,United States,6.0
2358,Hibob,Tel Aviv,HR,70.0,0.30,3/30/2020,Series A,Israel,45.0
2359,Casper,New York City,Retail,NaN,NaN,9/14/2021,Post-IPO,United States,339.0
2360,Wildlife Studios,Sao Paulo,Consumer,300.0,0.20,11/28/2022,Unknown,Brazil,260.0

In [112]:
df['company']

0                           Atlassian
1                            SiriusXM
2                              Alerzo
3                              UpGrad
4                                Loft
5                       Embark Trucks
6                               Lendi
7                         UserTesting
8                              Airbnb
9                            Accolade
10                             Indigo
11                            Zscaler
12                        MasterClass
13                         Ambev Tech
14                              Fittr
15                               CNET
16                           Flipkart
17                            Kandela
18                      Truckstop.com
19                       Thoughtworks
20                              iFood
21                       Color Health
22                              Waymo
23                             PayFit
24                          Yellow.ai
25                             Sonder
26                 Protego Trust Bank
27                    Electronic Arts
28                         Eventbrite
29                      DUX Education
30                       MeridianLink
31                        Sono Motors
32                           Cerebral
33                             Amount
34                           Palantir
35                           Outreach
36                             Stytch
37                           BitSight
38                            Twitter
39                           Ericsson
40                           SAP Labs
41                     Velodyne Lidar
42                           Medallia
43                           Eat Just
44                      Lucira Health
45                               Stax
46                           Poshmark
47                           Merative
48                        OneFootball
49                         The Iconic
50                               EVgo
51                           StrongDM
52                        Dapper Labs
53                            Messari
54                     Vibrent Health
55                          Synamedia
56                             TaskUs
57                      Arch Oncology
58                          Immutable
59                Jounce Therapeutics
60                         Locomation
61                            Polygon
62                        Crunchyroll
63                         Ethos Life
64                               Bolt
65                             Criteo
66                         Green Labs
67                         PeerStreet
68                            Zalando
69                             MyGate
70                         Fireblocks
71                              Kinde
72                             Fipola
73                                 HP
74                            Tencent
75                           Evernote
76                       Chipper Cash
77                           Digimarc
78                            Reserve
79                           DocuSign
80                   Pico Interactive
81                       The RealReal
82                         Smartsheet
83                             Convoy
84                                Wix
85                       ServiceTitan
86                               Neon
87                         Jellysmack
88                       DigitalOcean
89                           Sprinklr
90                         Betterment
91                        Divvy Homes
92                            Milkrun
93                          Momentive
94                         Observe.AI
95                 Religion of Sports
96                             Tackle
97                 Vicarious Surgical
98                        CommerceHub
99                        HackerEarth
100                        PhableCare
101                             Udemy
102                            Twilio
103                          Electric
104                       EMX Digital
105                           PetLove
106                            iRobot
107                 Collective Health
108                        Magic Eden
109                            Casavo
110                         Foodpanda
111                             Getir
112                          LinkedIn
113                           Moladin
114                        TripleLift
115                      TikTok India
116                           Open Co
117                 Rigetti Computing
118                             Yahoo
119                    Misfits Market
120                         Deliveroo
121                          Olive AI
122                           Oportun
123                            GitLab
124                              Bark
125                      Nomad Health
126                            Veriff
127                    REE Automotive
128                            GitHub
129                            Quillt
130                           WeTrade
131                           GoDaddy
132                            Affirm
133                             Gusto
134                              Gong
135                     Beam Benefits
136                         Equitybee
137                            Baraja
138                              Koho
139                             Medly
140                           Nearmap
141                              Zoom
142                              eBay
143                       SecureWorks
144                         Salesloft
145                           Openpay
146                         LearnUpon
147                     Sana Benefits
148                              Dell
149                             Loggi
150                      Catch.com.au
151                        VinFast US
152                             Drift
153                       Pocket Aces
154                             Clari
155                           C6 Bank
156                             Daraz
157                           TenureX
158                            Kyruus
159                          Lightico
160                            FarEye
161                     Protocol Labs
162                            Finder
163                            Byju's
164                              Okta
165                          Autodesk
166                        Mindstrong
167                         NCC Group
168                              Miro
169                             Getir
170                          Highspot
171                           Bittrex
172                          Snowplow
173                        Articulate
174                     Desktop Metal
175                         Getaround
176                            NCSoft
177                          Talkdesk
178                            Splunk
179                         Pinterest
180                        DraftKings
181                             Cyren
182                           Workato
183                     VerticalScope
184                             Wheel
185                       Chainalysis
186                           Appgate
187                           Exterro
188                          TheSkimm
189                               Ada
190              Bustle Digital Group
191            Frequency Therapeutics
192                           MariaDB
193                       Match Group
194                       Omnipresent
195                            Picnic
196                            Rivian
197                            PayPal
198                            NetApp
199                           Workday
200                           HubSpot
201                           Upstart
202                       Software AG
203                              Wish
204                             Wefox
205                     Tilting Point
206                            Gokada
207                           AU10TIX
208              National Instruments
209                          OpenText
210                           Philips
211                         OLX Group
212                           Arrival
213                           Groupon
214                             Intel
215                             Glovo
216                     Delivery Hero
217             Impossible Foods copy
218                          Chrono24
219                   BM Technologies
220                             Olist
221                            Oyster
222                       Prime Trust
223                        Quantum SI
224                              SoFi
225                           Hoxhunt
226                          Me Poupe
227                       CoinTracker
228                            SSense
229                         DealShare
230                          Ruggable
231                          Synopsys
232                            Heycar
233                        Matrixport
234                          Shakepay
235                             #Paid
236                            Decent
237                           Feedzai
238                              Nate
239                               SAP
240                         Confluent
241                       DriveWealth
242                       Mode Global
243                 Plus One Robotics
244                             Quora
245                               IBM
246                      Lam Research
247                        Shutterfly
248                              Luno
249                     Clear Capital
250                   Guardant Health
251                        SirionLabs
252                     Tier Mobility
253                           CareRev
254                          Finastra
255                              Noom
256                         PagSeguro
257                            Prosus
258                            Vacasa
259                        Innovaccer
260                              Bolt
261                      PartnerStack
262                            Gitpod
263                      OFFOR Health
264                          Venngage
265                          CoachHub
266                  Corvus Insurance
267                              Icon
268                         PagerDuty
269                             Scoro
270                           Spotify
271                      Uber Freight
272                            Inmobi
273                           Innovid
274                         Booktopia
275                           Ermetic
276                           Namogoo
277                          Camp K12
278                            Gemini
279                              Yext
280                               BUX
281                            Google
282                           Wayfair
283                            Swiggy
284                         MediBuddy
285                         Vox Media
286                        BitTorrent
287                             Karat
288                            Enjoei
289                           Edifecs
290               Citrine Informatics
291                           Avalara
292               Cyteir Therapeutics
293                   Morning Consult
294                            TikTok
295                            Zappos
296                       Capital One
297                          Proterra
298                           WeWork
299                            Hubilo
300                          Saks.com
301                          CS Disco
302                        Riot Games
303                            Hydrow
304                       Earth Rides
305                            Fandom
306                      IAM Robotics
307                           Icertis
308                           Magnite
309                            Mudafy
310                        Personalis
311                            Prisma
312                         Spaceship
313                           Wallbox
314                         Microsoft
315                            Sophos
316                    Teladoc Health
317                             Vroom
318                               8x8
319                            Pagaya
320                          Benevity
321                         Inspirato
322                         Jumpcloud
323                             nCino
324                            Starry
325                         Hootsuite
326                              Clue
327                           Addepar
328                    80 Acres Farms
329                             Aiven
330               Bally's Interactive
331                         Betterfly
332                             Cazoo
333                              Coda
334                        Cypress.io
335                 Lucid Diagnostics
336                           Mavenir
337                         Redbubble
338               Lightspeed Commerce
339                             Unity
340                       Britishvolt
341                            Clutch
342                            Exotel
343                             Unico
344                               Tul
345                 American Robotics
346                   Luxury Presence
347                       RingCentral
348                         Fishbrain
349                        GoMechanic
350                           LiveVox
351                            Oracle
352                             Rappi
353                        RateGenius
354                                XP
355                           PagBank
356                         ShareChat
357                        Gramophone
358                           ClearCo
359                             Dunzo
360                          Ignition
361                       Rebel Foods
362                    Captain Fresh
363                            Snappy
364                        BharatAgri
365                            DeHaat
366                       Black Shark
367                               Ola
368                         Bonterra
369                              Vial
370                     Arch Oncology
371                           Carvana
372                        CoSchedule
373                          GoCanvas
374                         Jellyfish
375                      Lending Club
376                         SmartNews
377                           Skit.ai
378                              Pier
379                    Blockchain.com
380                        Greenlight
381                 Cashfree Payments
382                            Mapbox
383             Definitive Healthcare
384                        Akili Labs
385                      Career Karma
386                        Crypto.com
387                           Lattice
388                           Life360
389                      Rock Content
390                          Flexport
391                         Qualtrics
392                            Verily
393                           Tipalti
394                             Jumio
395                           CoinDCX
396                         HashiCorp
397                            Embark
398                         Intrinsic
399                           Citizen
400                             Carta
401                           Limeade
402                            Oyster
403                            Paddle
404                          Coinbase
405                       Informatica
406                             Blend
407                     Till Payments
408                         ConsenSys
409                         ForeScout
410                         Thinkific
411                              LEAD
412                            Parler
413                            GoBolt
414                           Relevel
415                    StreamElements
416                       100 Thieves
417                           Beamery
418                          Cart.com
419                            Citrix
420                             Esper
421                             WHOOP
422                 Fate Therapeutics
423              Century Therapeutics
424                   Editas Medicine
425                          Scale AI
426                      Minute Media
427                            WalkMe
428                             Huobi
429                     Carbon Health
430                            Bounce
431                             Aware
432                         CareerArc
433                          CreateMe
434                           Lantern
435                       Mojo Vision
436                         SuperRare
437                               Cue
438                        SoundHound
439                            Socure
440                           Genesis
441                            Moglix
442                           Twitter
443                          Everlane
444                          Pecan AI
445                       Personetics
446                  Twine Solutions
447                          UpScalio
448                         Attentive
449                           Compass
450                          Megaport
451                        Stitch Fix
452                              TCR2
453                            Amazon
454                        Salesforce
455                        Astronomer
456                           Kaltura
457                            Augury
458                 Butterfly Network
459                             Vimeo
460                              Wyre
461                       Pegasystems
462                          Uniphore
463                           Harappa
464                         ByteDance
465                            Amdocs
466                          Bilibili
467                   Octopus Network
468                              PayU
469                           Element
470                            Willow
471                       Back Market
472                            Zoopla
473                          Qualcomm
474                          TuSimple
475                            Lendis
476                             Chope
477                             Briza
478                        StreetBees
479                             Zhihu
480                           Homebot
481                         Health IQ
482                            Xiaomi
483                        YourGrocer
484                          Tomorrow
485                          Revelate
486                            E Inc.
487                         Autograph
488                        Improbable
489                   Modern Treasury
490                             Reach
491                        SonderMind
492                       BigCommerce
493                        Freshworks
494                          LeafLink
495                        Workmotion
496                            Apollo
497                             JD.ID
498                         GoStudent
499                  Quanergy Systems
500                         Headspace
501                           ChowNow
502                           Landing
503                         Thumbtack
504                             Edgio
505                     Komodo Health
506                             Viant
507                            TaxBit
508                       Pluralsight
509                           Freshly
510                             Balto
511                           Caribou
512                         Outschool
513                           Xentral
514                         Autobooks
515                           Convene
516                         PharmEasy
517                          Playtika
518                         Share Now
519                             Alice
520                            Primer
521                       OneFootball
522                              C2FO
523                        Brodmann17
524                     Digital Surge
525               N-able Technologies

In [114]:
df.loc[3]

company                     UpGrad
location                    Mumbai
industry                 Education
total_laid_off               120.0
percentage_laid_off            NaN
date                      3/6/2023
stage                      Unknown
country                      India
funds_raised_millions        631.0
Name: 3, dtype: object

In [116]:
df.iloc[3]

company                     UpGrad
location                    Mumbai
industry                 Education
total_laid_off               120.0
percentage_laid_off            NaN
date                      3/6/2023
stage                      Unknown
country                      India
funds_raised_millions        631.0
Name: 3, dtype: object